//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Alu_Id { get; set; }
        public int User_Id { get; set; }
        public Nullable<System.DateTime> Alu_FechNac { get; set; }
        public string Alu_Apoderado { get; set; }
        public System.DateTime Alu_FechIngreso { get; set; }
        public bool Alu_Estado { get; set; }
        public string Alu_Foto { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
