//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno()
        {
            this.Calificacion = new HashSet<Calificacion>();
            this.Matricula = new HashSet<Matricula>();
            this.Recibo = new HashSet<Recibo>();
        }
    
        public int Alu_Id { get; set; }
        public int User_Id { get; set; }
        public string Alu_Apoderado { get; set; }
        public Nullable<bool> Alu_Estado { get; set; }
        public string Alu_Foto { get; set; }
        public System.DateTime Alu_FechaIngreso { get; set; }
        public System.DateTime Alu_FechaRegistro { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual ICollection<Recibo> Recibo { get; set; }
    }
}
