//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        public Aula()
        {
            this.Programacion = new HashSet<Programacion>();
        }
    
        public int Aul_Id { get; set; }
        public string Aul_Capacidad { get; set; }
    
        public virtual ICollection<Programacion> Programacion { get; set; }
    }
}
