//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        public Aula()
        {
            this.Programa = new HashSet<Programa>();
        }
    
        public int AulId { get; set; }
        public Nullable<int> AulNumero { get; set; }
        public Nullable<int> AulCapacidad { get; set; }
    
        public virtual ICollection<Programa> Programa { get; set; }
    }
}
