//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Calificacion = new HashSet<Calificacion>();
            this.Matricula = new HashSet<Matricula>();
            this.ModuloCurso = new HashSet<ModuloCurso>();
            this.Profesor = new HashSet<Profesor>();
            this.Recibo = new HashSet<Recibo>();
        }
    
        public int CurId { get; set; }
        public string CurName { get; set; }
        public Nullable<int> CurNumHoras { get; set; }
        public Nullable<decimal> CurPrecio { get; set; }
    
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual ICollection<ModuloCurso> ModuloCurso { get; set; }
        public virtual ICollection<Profesor> Profesor { get; set; }
        public virtual ICollection<Recibo> Recibo { get; set; }
    }
}
