//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.Programacion = new HashSet<Programacion>();
        }
    
        public int Hor_Id { get; set; }
        public string Hor_Grupo { get; set; }
        public Nullable<System.TimeSpan> Hor_Ini { get; set; }
        public string Hor_Dia { get; set; }
        public string Hor_Turno { get; set; }
        public Nullable<System.TimeSpan> Hor_Fin { get; set; }
    
        public virtual ICollection<Programacion> Programacion { get; set; }
    }
}
