//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int Mat_Id { get; set; }
        public int Cur_Id { get; set; }
        public int User_Id { get; set; }
        public int Rec_Id { get; set; }
        public string Mat_Tipo { get; set; }
        public System.DateTime Mat_Fecha { get; set; }
        public bool Mat_Estado { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Recibo Recibo { get; set; }
    }
}
