//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int MatriId { get; set; }
        public int ProgId { get; set; }
        public int ModId { get; set; }
        public int CurId { get; set; }
        public int Alu_Id { get; set; }
        public int RecId { get; set; }
        public System.DateTime MatriFecha { get; set; }
        public bool MatriEstado { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Modulo Modulo { get; set; }
        public virtual Programa Programa { get; set; }
        public virtual Recibo Recibo { get; set; }
    }
}
