//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.Calificacion = new HashSet<Calificacion>();
            this.Matricula = new HashSet<Matricula>();
            this.ModuloCurso = new HashSet<ModuloCurso>();
            this.Programa = new HashSet<Programa>();
            this.Recibo = new HashSet<Recibo>();
        }
    
        public int ModId { get; set; }
        public int ModCatId { get; set; }
        public int ModNivelId { get; set; }
        public string ModNombre { get; set; }
        public int ModNumHoras { get; set; }
        public int ModNumMes { get; set; }
        public int ModNumCursos { get; set; }
    
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual ModuloCategoria ModuloCategoria { get; set; }
        public virtual ModuloNivel ModuloNivel { get; set; }
        public virtual ICollection<ModuloCurso> ModuloCurso { get; set; }
        public virtual ICollection<Programa> Programa { get; set; }
        public virtual ICollection<Recibo> Recibo { get; set; }
    }
}
