//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloCurso
    {
        public int ModCurRegistroId { get; set; }
        public Nullable<System.DateTime> MCFechaRegistro { get; set; }
        public int ModId { get; set; }
        public int CurId { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Modulo Modulo { get; set; }
    }
}
