//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloCategoria
    {
        public ModuloCategoria()
        {
            this.Modulo = new HashSet<Modulo>();
        }
    
        public int ModCatId { get; set; }
        public string ModCatNombre { get; set; }
        public string ModCatDescripcion { get; set; }
    
        public virtual ICollection<Modulo> Modulo { get; set; }
    }
}
