//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloNivel
    {
        public ModuloNivel()
        {
            this.Modulo = new HashSet<Modulo>();
        }
    
        public int ModNivelId { get; set; }
        public string ModNivelNombre { get; set; }
        public string ModNivelDescripcion { get; set; }
    
        public virtual ICollection<Modulo> Modulo { get; set; }
    }
}
