//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoId { get; set; }
        public int RecId { get; set; }
        public System.DateTime PagoFecha { get; set; }
        public Nullable<decimal> PagoDescuento { get; set; }
        public decimal PagoMonto { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Recibo Recibo { get; set; }
    }
}
