//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public int Prof_Id { get; set; }
        public Nullable<int> Per_Id { get; set; }
        public string Prof_Especialidad { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
