//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public Profesor()
        {
            this.Calificacion = new HashSet<Calificacion>();
        }
    
        public int Prof_Id { get; set; }
        public int User_Id { get; set; }
        public int Cur_Id { get; set; }
        public string Prof_Especialidad { get; set; }
        public string Prof_Procedencia { get; set; }
        public string Prof_LugarEstudio { get; set; }
    
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
