//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa
    {
        public int ProgId { get; set; }
        public string ProgNombre { get; set; }
        public string ProgDescripcion { get; set; }
        public System.DateTime ProgFechaRegistro { get; set; }
        public System.DateTime ProgFechaInicio { get; set; }
        public System.DateTime ProgFechaFin { get; set; }
        public int ModId { get; set; }
        public int AulId { get; set; }
        public int HorId { get; set; }
        public Nullable<bool> EsVigente { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Modulo Modulo { get; set; }
    }
}
