//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public Recibo()
        {
            this.Matricula = new HashSet<Matricula>();
            this.Pago = new HashSet<Pago>();
        }
    
        public int RecId { get; set; }
        public int Alu_Id { get; set; }
        public int ModId { get; set; }
        public int CurId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual Modulo Modulo { get; set; }
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
