//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public Recibo()
        {
            this.Matricula = new HashSet<Matricula>();
        }
    
        public int Rec_Id { get; set; }
        public int User_Id { get; set; }
        public int Pag_Id { get; set; }
    
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
