//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Administrador = new HashSet<Administrador>();
            this.Alumno = new HashSet<Alumno>();
            this.Profesor = new HashSet<Profesor>();
        }
    
        public int User_Id { get; set; }
        public int Per_Id { get; set; }
        public int TipoUser_Id { get; set; }
        public string User_Nombre { get; set; }
        public string User_Pass { get; set; }
        public Nullable<bool> User_Inactivo { get; set; }
    
        public virtual ICollection<Administrador> Administrador { get; set; }
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Profesor> Profesor { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
